version: 2
jobs:
  build:
    working_directory: ~/closex
    docker:
      - image: elixir:1.5
        environment:
          COVERALLS_REPO_TOKEN: 3T8c9tUBXMAmGPmnBO1SUv7xGFr32gbLs
          MIX_ENV: test

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: elixir --version
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix coveralls.circle

